### PR TITLE
Fix external ref

### PR DESCRIPTION
**Pull request by lfern**
fix external reference to get schema definition in other files

### CODE REVIEW

**Comment by vearutop** [comment]
Hi @lfern, thanks for your pull request. 
Could you please bring more context on the issue by adding a test?

**Comment by lfern** [comment]
I don't have much experience in json schems, and maybe I am doing something wrong, but I want to parse a schema splitted in multiple files. If I try to reuse a definitiont in other file like this:

```javascript
{
  "options" : {
            "$ref": "JobTemplate.json#/definitions/instanceOptions"
        }
}
```
and in JobTemplate.json 
```javascript
{
    "type": "object",
    "required" :["f"],
    "properties":{
        "f" : {
            "type" : "integer"
        }
    },
    "definitions" :{
        "instanceOptions" : {
            "type" : "object",
            "required" :[],
            "properties" :{
                "m" : {
                }
            }
        }
     }
}
```
When you invoke JsonPointer::splitPath you get "JobTemplate.json#", not "#" as expected. And if you try to reference root schema object `"$ref": "JobTemplate.json#/"` You have to remove slash character so when you invoke JsonPointer::add you assign the root schema element.

And https://github.com/swaggest/php-json-schema/pull/61/files#diff-955333433435f618159f19b213683493R177 is needed to reference root object in another schema file.

**Comment by vearutop** [comment]
@lfern happy new year and sorry for late reply, I was unable to reproduce an issue that you likely are trying to solve: https://github.com/swaggest/php-json-schema/commit/04b783672d997764e329d54d48f610e0718af58a.

Could you add more details here if it is still relevant?

**Comment by lfern** [comment]
Here you can see the way I am using swagger. I have multiple schema files and I only have to "declare" or import de json schema with "root" declarations. With this modification you don't have to preload all json files, they can be resolved from directory containing all files (maybe I am doing something wrong):

https://gist.github.com/lfern/3de53c648feb10f92d0824fe218fa12d

**Comment by vearutop** [comment]
@lfern I've tried to reproduce your test case and it seem to work ok (please check the commit https://github.com/swaggest/php-json-schema/commit/f10410569e024cadb8c4207c60deb7da431bdb4e), recently there were few changes to local resolver that might fix your issue.

**Comment by vearutop** [comment]
Closing as it does not seem to be relevant with up to date state of code.

**Pull request closed without merging**
