### PR TITLE
repair BasicFetcher

### PR DESCRIPTION
**Pull request by filipekp**
$ref for external https remote source

### CODE REVIEW

**Comment by vearutop** [comment]
Not sure what is making those leading spaces, but no worries, I'll fix myself later. :)

image

**Comment by vearutop** [comment]
Thank you, tagged [v0.12.17](https://github.com/swaggest/php-json-schema/releases/tag/v0.12.17).

**Comment by cs278** [comment]
This change disables SSL/TLS certificate validation?!

**Comment by vearutop** [comment]
Yes, it is quite common to have self-signed certs for internal services, so allowing invalid certificates by default removes some friction.

But now, that you asked this question with exclamation mark, I start thinking that maybe the security cost is underestimated. 🤔 

@cs278 could you expand your concern (if any) in context of your use case?

May be this change has to be reimplemented as an explicit `UnsafeFetcher`.

**Comment by martin-juul** [comment]
Usually you would trust your self signed root ca on your host.

**Pull request merged**
