### PR TITLE
Fix nullable fields

### PR DESCRIPTION
**Pull request by bruceoutdoors**
Change in https://github.com/swaggest/php-json-schema/pull/147 causes nullable JSON fields not to be exported.

This change should fix that.

### CODE REVIEW

**Comment by vearutop** [comment]
Could you rebase or merge latest master in your branch (this should fix CI)?

**Comment by bruceoutdoors** [comment]
Ok done

**Review by jpwijbenga — COMMENTED** [review]
This seems wrong. Line 110 is still there, right? $value is assigned once and overwritten directly after that.

**Comment by vearutop** [comment]
I think you're right, though maybe the final behavior is somewhat similar (if not raising a notice). Removing line 110 seems reasonable.

**Pull request merged**
